# Serving HTML through API Gateway for AWS Lambda
service: aul 

provider:
  name: aws
  runtime: nodejs4.3

functions:
  aul:
    handler: handler.html
    events:
      - http:
          method: get
          path: / 
